# Generated by Django 4.1 on 2024-01-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0002_people'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='Peoples',
        ),
    ]
