# Generated by Django 4.1 on 2024-01-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourapp', '0003_rename_people_peoples'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peoples',
            new_name='People',
        ),
    ]
